{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "ivory.fullname" . }}
  labels:
    {{- include "ivory.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "ivory.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "ivory.selectorLabels" . | nindent 14 }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              ivory.io/rpc-client: "true"
        {{- range .Values.networkPolicy.rpcFrom }}
        - {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- range .Values.networkPolicy.kubeletCidrs }}
        - ipBlock:
            cidr: {{ . | quote }}
        {{- end }}
      ports:
        - protocol: TCP
          port: {{ .Values.rpc.servicePort }}
    - from:
        - podSelector:
            matchLabels:
              {{- include "ivory.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.p2p.port }}
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - podSelector:
            matchLabels:
              {{- include "ivory.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.p2p.port }}
{{- end }}
