{{- if or .Values.validatorKey .Values.rpc.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ivory.fullname" . }}
  labels:
    {{- include "ivory.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.validatorKey }}
  validator.key: {{ .Values.validatorKey | quote }}
  {{- end }}
  {{- if .Values.rpc.token }}
  rpc-token: {{ .Values.rpc.token | quote }}
  {{- end }}
{{- end }}
