# crates/ivory-vm/Cargo.toml
[package]
name = "ivory-vm"
version.workspace = true
edition.workspace = true

[dependencies]
ivory-primitives = { workspace = true }
ivory-core = { workspace = true }
ivory-state = { workspace = true }
thiserror = { workspace = true }
wasmi = { workspace = true }

[dev-dependencies]
wat = { workspace = true }
